import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { getAllProducts, Product } from "services/product";

const Home: NextPage<{ products: Product[] }> = ({ products }) => {
  return (
    <>
      <Head>
        <title>Sellit.ng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Sellit.ng</h1>

      <pre>{JSON.stringify(products, null, 2)}</pre>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { products }: { products: Product[] } = await getAllProducts();

  // if (!products) {
  //   return {
  //     notFound: true,
  //   };
  // }

  return {
    props: {
      products,
    },
  };
};
export default Home;
